# Generated by Django 3.1.5 on 2021-01-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_air'),
    ]

    operations = [
        migrations.CreateModel(
            name='airr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('a', models.CharField(max_length=60)),
                ('b', models.CharField(max_length=60)),
            ],
        ),
    ]
