# Generated by Django 3.1.5 on 2021-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20210113_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Carbon_Monoxide', models.CharField(max_length=60)),
                ('NOx', models.CharField(max_length=60)),
                ('Ozone', models.CharField(max_length=60)),
                ('Particulate_Matter', models.CharField(max_length=60)),
                ('SOx', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveIntegerField()),
                ('E_Coliform', models.CharField(max_length=60)),
                ('Total_Coliform', models.CharField(max_length=60)),
                ('Temperature', models.CharField(max_length=60)),
                ('pH', models.CharField(max_length=60)),
                ('Turbidity', models.CharField(max_length=60)),
                ('Dissolved_Oxygen', models.CharField(max_length=60)),
                ('Conductivity', models.CharField(max_length=60)),
                ('Total_Dissolved_Solids', models.CharField(max_length=60)),
                ('Total_Suspended_Solids', models.CharField(max_length=60)),
                ('Total_Hardness', models.CharField(max_length=60)),
                ('Biological_Oxygen_Demand', models.CharField(max_length=60)),
                ('Arsenic', models.CharField(max_length=60)),
                ('Aluminium', models.CharField(max_length=60)),
                ('Boron', models.CharField(max_length=60)),
                ('Chloride', models.CharField(max_length=60)),
                ('Chromium', models.CharField(max_length=60)),
                ('Copper', models.CharField(max_length=60)),
                ('Cyanide', models.CharField(max_length=60)),
                ('Fluoride', models.CharField(max_length=60)),
                ('Lead', models.CharField(max_length=60)),
                ('Nickel', models.CharField(max_length=60)),
                ('Nitrate', models.CharField(max_length=60)),
                ('Nitrite', models.CharField(max_length=60)),
                ('Chlorine', models.CharField(max_length=60)),
                ('Zinc', models.CharField(max_length=60)),
                ('COD', models.CharField(max_length=60)),
                ('Sulphate', models.CharField(max_length=60)),
                ('Sulphide', models.CharField(max_length=60)),
                ('Cadmium', models.CharField(max_length=60)),
                ('Nickle', models.CharField(max_length=60)),
                ('Iron', models.CharField(max_length=60)),
                ('Ammonium', models.CharField(max_length=60)),
                ('Manganese', models.CharField(max_length=60)),
                ('Phenol', models.CharField(max_length=60)),
            ],
        ),
    ]
