# Generated by Django 3.1.5 on 2021-01-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
