# Generated by Django 3.1.5 on 2021-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210124_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='Carbon_Monoxide',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='air',
            name='NOx',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='air',
            name='Ozone',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='air',
            name='Particulate_Matter',
            field=models.IntegerField(max_length=60),
        ),
        migrations.AlterField(
            model_name='air',
            name='SOx',
            field=models.IntegerField(max_length=60),
        ),
    ]
